# 基本设置
title: JZW 加密货币资讯站
SEOTitle: JZW 加密货币资讯 | 特朗普币价格 | USDT汇率 | OKX交易所 | Pi币行情
description: "专注于加密货币实时价格追踪、USDT汇率换算、OKX交易所使用指南、Pi Network价格分析、Web3钱包教程的专业博客，提供特朗普币、比特币、以太坊等数字货币最新行情资讯。"
keyword: "特朗普币实时价格，USDT汇率人民币，USDT to CNY，OKX交易所，欧易交易所，OKX Web3钱包，Pi币价格，Pi coin price today，Pi Network，ETH美元，Bitcoin to USD，Tether新闻，AAVE USDT，ETH to PKR，USDT to RUB，GBP to USDT，OKX可用性，OKX转账教程，区块链钱包，加密货币行情，数字货币资讯，去中心化金融，Web3博客"
url: "https://jzwojy7.github.io"
baseurl: ""
github_username:    jzwojy7
header-img: img/post-bg-desk.jpg

# 构建设置
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10

# 插件
plugins:
  - jekyll-paginate

# 排除文件
exclude:
  - README.md
  - Gruntfile.js
  - package.json
  - node_modules
  - less
